Show help in fzf_preview

diff --git a/fontpreview b/fontpreview
--- a/fontpreview
+++ b/fontpreview
@@ -10,8 +10,10 @@ FONTPREVIEW_DIR="$(mktemp -d --tmpdir fontpreview_dir_XXXXXXXX)"
 PIDFILE="$(mktemp --tmpdir="$FONTPREVIEW_DIR" fontpreview_XXXXXXXX.pid)"
 FONT_PREVIEW="$(mktemp --tmpdir="$FONTPREVIEW_DIR" fontpreview_XXXXXXXX.png)"
 TERMWIN_IDFILE="$(mktemp --tmpdir="$FONTPREVIEW_DIR" fontpreview_XXXXXXXX.termpid)"
+export SHOW_HELP_FLAG_FILE="$(mktemp --tmpdir="$FONTPREVIEW_DIR" fontpreview_help_flag_XXXXXXXX)" 
 VERSION=1.0.3
 
+BASH="$(which bash)"
 CACHE_DIR="$HOME/.cache/fontpreview"
 PREVIEW_TEXT_FILE="$CACHE_DIR/preview_text"
 
@@ -69,8 +71,33 @@ generate_preview(){
         -flatten "$FONT_PREVIEW"
 }
 
+fzf_preview() {
+    help_mesg='┌─┐┌─┐┌┐┌┌┬┐┌─┐┬─┐┌─┐┬  ┬┬┌─┐┬ ┬
+├┤ │ ││││ │ ├─┘├┬┘├┤ └┐┌┘│├┤ │││
+└  └─┘┘└┘ ┴ ┴  ┴└─└─┘ └┘ ┴└─┘└┴┘
+    
+-- Very customizable and minimal font previewer written in bash --
+    
+Shortkey:
+  Ctrl-y: Copy font name.
+  Ctrl-t: Edit preview text. {
+    ENTER    : Print query.
+    Alt-ENTER: Use selected history item as preview text.
+    Ctrl-t: Go Back.
+    }
+  Ctrl-i: Toggle fonts basic infomation page.
+  Ctrl-h: Toggle help.
+  Enter : Preview selected font.'
+    
+    if [ $(cat "$SHOW_HELP_FLAG_FILE" 2> /dev/null ) -eq 1 ] 2> /dev/null; then
+        echo "$help_mesg"
+    else
+        convert -list font | sed -n "/^[ ]*Font: $@$/,+5p"
+    fi
+}
+
 main(){
-    # Checkig if needed dependencies are installed  
+    # Checkig if needed dependencies are installed
     dependencies=(xdotool sxiv convert fzf xclip)
     for dependency in "${dependencies[@]}"; do
         type -p "$dependency" &>/dev/null || {
@@ -81,7 +108,8 @@ main(){
     
     # Checking if needed folder or file are created
     [ -d "$CACHE_DIR" ] || mkdir -p "$CACHE_DIR"
-	  [ -f "$PREVIEW_TEXT_FILE" ] || echo "$PREVIEW_TEXT" > "$PREVIEW_TEXT_FILE"
+    [ -f "$PREVIEW_TEXT_FILE" ] || echo "$PREVIEW_TEXT" > "$PREVIEW_TEXT_FILE"
+    echo 0 > "${SHOW_HELP_FLAG_FILE}"
 
     # Checking for enviornment variables which the user might have set.
     # This config file for fontpreview is pretty much the bashrc, zshrc, etc
@@ -104,114 +132,85 @@ main(){
     # Flag to run some commands only once in the loop
     FIRST_RUN=true
 
-    
     # Default value of the font
     font=$(convert -list font |  awk -F: '/^\s *Font: /{print substr($NF,2)}' | head -1)
-    
-
-
-	  help_mesg='
-        ┌─┐┌─┐┌┐┌┌┬┐┌─┐┬─┐┌─┐┬  ┬┬┌─┐┬ ┬
-        ├┤ │ ││││ │ ├─┘├┬┘├┤ └┐┌┘│├┤ │││
-        └  └─┘┘└┘ ┴ ┴  ┴└─└─┘ └┘ ┴└─┘└┴┘
-
--- Very customizable and minimal font previewer written in bash --
-
-Shortkey:
-    Ctrl-y: Copy font name.
-    Ctrl-t: Edit PREVIEW_TEXT. {
-	      ENTER : Print query.
-	      Ctrl-s: Accept selected history.
-	      Ctrl-t: Go Back.
-    }
-    Ctrl-i: Toggle fonts basic infomation page.
-    Ctrl-h: Toggle help.
-    Enter : Preview selected font.'
-
-	  # The items in this menu shouldn't have any space.
-	  extra_menu=(
-		    copy_font_info
-	  )
-
     _fzf_bind_copy_name='ctrl-y:execute(echo -n {} | xclip -selection clipboard)'
     _fzf_bind_echo_name='enter:execute(echo font -- {})'
-    _fzf_bind_edit_preview_text="ctrl-t:execute(echo -E preview_text -- \$( cat \"$PREVIEW_TEXT_FILE\"  | fzf --bind=\"ctrl-t:abort,ctrl-s:accept,enter:print-query\" ) )"
+    _fzf_bind_edit_preview_text="ctrl-t:execute(echo -E preview_text -- \$( cat \"$PREVIEW_TEXT_FILE\"  | fzf --bind=\"ctrl-t:abort,alt-enter:accept,enter:print-query\" ) )"
     _fzf_bind_tog_preview='ctrl-i:toggle-preview'
-    _fzf_bind_help_mesg="ctrl-h:execute( echo \$( printf '%s\n' \"${extra_menu[@]}\" | fzf --preview='{echo \"$help_mesg\"}' --preview-window=top:60%:wrap --bind='ctrl-h:abort') -- {})"
+    _fzf_bind_tog_help="ctrl-h:execute( [ \$(cat $SHOW_HELP_FLAG_FILE 2> /dev/null ) -eq 1 ] && echo 0 > $SHOW_HELP_FLAG_FILE || echo 1 > $SHOW_HELP_FLAG_FILE )+toggle-preview+toggle-preview"
 
-    _fzf_preview="{convert -list font | sed -n '/^[ ]*Font: {}$/,+5p'}"
-    _fzf_preview_opt="up:30%:wrap:hidden"
-	  _fzf_header="Hit <Ctrl-h> to see help"
-	  
+    _fzf_preview_opt="right:50%:wrap"
+    _fzf_header='Hit Ctrl-h to show help.'
+    
+    export SHELL="$BASH"
+    export -f fzf_preview
     # Start a co-process, everytime you press [ENTER], this process will echo
     # "font -- <font name>" in the background. And the command =read t <&{COPROC[0]}=
     # will get data: "font -- <font name>"
     # Jump into a new fzf page to edit PREVIEW_TEXT if you press [Ctrl-t] in the
-    # fzf page of font 
+    # fzf page of font
     # List out all the fonts which imagemagick is able to find, extract
     # the font names and then pass them to fzf
-    coproc { convert -list font | awk -F: '/^[ ]*Font: /{print substr($NF,2)}' | fzf --prompt="$SEARCH_PROMPT" --header="$_fzf_header" --preview="$_fzf_preview" --preview-window="$_fzf_preview_opt" --bind="$_fzf_bind_copy_name,$_fzf_bind_echo_name,$_fzf_bind_edit_preview_text,$_fzf_bind_tog_preview,$_fzf_bind_help_mesg"; }
+
+    coproc { ( convert -list font | awk -F: '/^[ ]*Font: /{print substr($NF,2)}' ) | fzf --prompt="$SEARCH_PROMPT" --header="$_fzf_header" --preview="fzf_preview {}" --preview-window="$_fzf_preview_opt" --bind="$_fzf_bind_copy_name,$_fzf_bind_echo_name,$_fzf_bind_edit_preview_text,$_fzf_bind_tog_preview,$_fzf_bind_tog_help"; }
     
     # Read data from the co-process in a loop, stop when getting nothing.
     while read -r t <&"${COPROC[0]}"; do
         case "$t" in
             'preview_text -- '*)
                 [ -n "${t#preview_text -- }" ] && PREVIEW_TEXT="${t#preview_text -- }"
-				        grep -F "$PREVIEW_TEXT" "$PREVIEW_TEXT_FILE" > /dev/null || echo "$PREVIEW_TEXT" >> "$PREVIEW_TEXT_FILE"
-				        ;;
+                grep -F "$PREVIEW_TEXT" "$PREVIEW_TEXT_FILE" > /dev/null || echo "$PREVIEW_TEXT" >> "$PREVIEW_TEXT_FILE"
+                ;;
             'font -- '*)
                 [ -n "${t#font -- }" ] && font="${t#font -- }"
                 ;;
-			      'copy_font_info -- '*)
-				        [ -n "${t#copy_font_info -- }" ] && convert -list font | sed -n "/^[ ]*Font: ${t#copy_font_info -- }\$/,+5p" | xclip -sel clip
-				        continue
-				        ;;
-			      *)
-				        continue
-				        ;;
+            *)
+                continue
+                ;;
         esac
-		
+
         # Exit if nothing is returned by fzf, which also means that the user
         # has pressed [ESCAPE]
         [[ -z $font ]] && return
 
         generate_preview "$font"
-		
-		if [ $FIRST_RUN == true ] || [ $(ps -p $(cat $PIDFILE) | tail -1 | awk '{print $4}') != sxiv ]; then
+
+        if [ $FIRST_RUN == true ] || [ $(ps -p $(cat $PIDFILE) | tail -1 | awk '{print $4}') != sxiv ]; then
             FIRST_RUN=false
 
             # Display the font preview using sxiv
             #sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &
             sxiv -N "fontpreview" -b -g "$SIZE$POSITION" "$FONT_PREVIEW" &
 
-			# Change focus from sxiv, back to the terminal window
+            # Change focus from sxiv, back to the terminal window
             # so that user can continue to search for fonts without
             # having to manually change focus back to the terminal window
             xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"
-			
-  			# Save the process ID so that we can kill
+
+            # Save the process ID so that we can kill
             # sxiv when the user exits the script
             echo $! >"$PIDFILE"
 
-	# Check for crashes of sxvi   
-	elif [ -f $PIDFILE ] ; then
-	    PID=$(cat $PIDFILE)
-	    if  [ ! -e /proc/$PID ] ; then
-		echo "Restart sxvi - You maybe using a obsolete version. " >&2
-		# Display the font preview using sxiv
-		sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &
-		
-		# Change focus from sxiv, back to the terminal window
-		# so that user can continue to search for fonts without
-		# having to manually change focus back to the terminal window
-		xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"
-		
-		# Save the process ID so that we can kill
-		# sxiv when the user exits the script
-		echo $! >"$PIDFILE"
-	    fi
-
-	fi
+            # Check for crashes of sxvi
+            elif [ -f $PIDFILE ] ; then
+            PID=$(cat $PIDFILE)
+            if [ ! -e /proc/$PID ] ; then
+                echo "Restart sxvi - You maybe using a obsolete version. " >&2
+                # Display the font preview using sxiv
+                sxiv -g "$SIZE$POSITION" "$FONT_PREVIEW" -N "fontpreview" -b &
+                
+                # Change focus from sxiv, back to the terminal window
+                # so that user can continue to search for fonts without
+                # having to manually change focus back to the terminal window
+                xdotool windowfocus "$(cat "$TERMWIN_IDFILE")"
+                
+                # Save the process ID so that we can kill
+                # sxiv when the user exits the script
+                echo $! >"$PIDFILE"
+            fi
+            
+        fi
     done
 }
 
@@ -227,7 +226,7 @@ options=$(getopt -o h --long position:,size:,version,search-prompt:,font-size:,b
 eval set -- "$options"
 
 while true; do
-    case "$1" in 
+    case "$1" in
         --size)
             shift;
             FONTPREVIEW_SIZE=$2
